# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [game, vice, pop, AA]
patreon: # Replace with a single Patreon username https://www.patreon.com/posts/22854182
open_collective: # Replace with a single Open Collective username Tornado.io 
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel -runtime
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username Casey
issuehunt: # Replace with a single IssueHunt username Denise3383
otechie: # Replace with a single Otechie username MIT
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://Walmart.com', 'https://jcpenny.com, https://justinfamily.famil.blog, https://ASPCA.org, https://godaddy.com']
